Change transaction section
hyperledger/iroha-api pull request #36
Opened 2017-12-19 14:42 UTC by neewy

In this section I have added explanation for transaction statuses, and expanded the explanation.

Please check it with ruby and bundle gem installed on your machine:
https://github.com/lord/slate/wiki/Installing-Slate#getting-set-up

2017-12-19 15:51 UTC, l4l reviewed
Maybe add in advance MST_EXPIRED status?

2017-12-19 16:22 UTC, luckychess requested changes

2017-12-19 16:22 UTC, luckychess commented on source/includes/_transactions.md
> +Transaction is a state-chaging set of actions in the system. When a transaction passes validation and consensus stages, it is written in block and saved in immutable block store (block chain).
chaging -> changing

2017-12-19 16:22 UTC, luckychess commented on source/includes/_transactions.md
> +Client applications should follow descibed protocol and form transactions accordingly to description below.
descibed -> described

2017-12-19 16:22 UTC, luckychess commented on source/includes/_transactions.md
> +    <li> Transaction counter. It counts how many times transaction creator send transactions in total. Counter is used to prevent replay attack, and is formed on client side </li>
sent I think

2017-12-19 16:22 UTC, luckychess commented on source/includes/_transactions.md
> +This section describes the set of states and mathes them with transaction lifecycle.
matches?

2017-12-19 16:22 UTC, luckychess commented on source/includes/_transactions.md
> + * `NOT_RECEIVED`: as client can query the peer, which may not have this transaction, the response indicates about such situation.
As far as I know, if peer does not know about transaction means there is no such transaction at all.

2017-12-19 16:39 UTC, kamilsa requested changes

2017-12-19 16:39 UTC, kamilsa commented on source/includes/_transactions.md
> +This section describes the set of states and mathes them with transaction lifecycle.
correct, no?

2017-12-19 16:42 UTC, neewy commented
Next time I will use grammarly before opening PR, thanks

2017-12-21 12:35 UTC, neewy commented
> Maybe add in advance MST_EXPIRED status?

@l4l I think that we should update docs in future as soon as we are merging the change in the repo

2017-12-21 12:50 UTC, luckychess approved these changes

2017-12-21 12:50 UTC, luckychess commented on source/includes/_transactions.md
> + * `NOT_RECEIVED`: the peer does not this transaction.
Verb missed (know about or something else)

2017-12-21 12:53 UTC, neewy commented on source/includes/_transactions.md
> + * `NOT_RECEIVED`: the peer does not this transaction.
sorry

2017-12-21 12:58 UTC, kamilsa requested changes

2017-12-21 12:58 UTC, kamilsa commented on source/includes/_transactions.md
> + * `NOT_RECEIVED`: the peer does not this transaction.
does not what?

2017-12-21 12:58 UTC, kamilsa commented on source/includes/_transactions.md
> + * `IN_PROGRESS`: the transaction is the part of a block, which is on voting during current consensus round.
If I am not mistaken, IN_PROGRESS means that transaction was received, but not processed.

2017-12-21 13:42 UTC, kamilsa approved these changes

2017-12-21 14:10 UTC, merged